apiVersion: v1
kind: Pod
metadata:
   name: my-secret-pod
spec:
   containers:
     - name: some-container
       image: tektutor/python-hello-ms:4.0 
       imagePullPolicy: Always
       env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
               name: mysecret 
               key:  username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
               name: mysecret 
               key:  password 
