apiVersion: v1
kind: Pod
metadata:
  name: another-pod
spec:
  containers:
    - name: another-pod
      image: redis
      volumeMounts:
        - name: my-data
          mountPath: "/etc/mydata"
          readOnly: true
  volumes:
    - name: my-data
      secret:
        secretName: mysecret 
